# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataviz_course',
                'doc_host': 'https://daniilgaltsev.github.io',
                'git_url': 'https://github.com/daniilgaltsev/dataviz_course',
                'lib_path': 'dataviz_course'},
  'syms': {'dataviz_course.core': {'dataviz_course.core.foo': ('core-copy1.html#foo', 'dataviz_course/core.py')}}}
