# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataviz_course',
                'doc_host': 'https://daniilgaltsev.github.io',
                'git_url': 'https://github.com/daniilgaltsev/dataviz_course',
                'lib_path': 'dataviz_course'},
  'syms': { 'dataviz_course.explore_data': { 'dataviz_course.explore_data.download_data': ( 'exploring_the_data.html#download_data',
                                                                                            'dataviz_course/explore_data.py')}}}
